# Generated by Django 4.1.2 on 2022-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('data', models.TextField(max_length=200, verbose_name='文章内容')),
            ],
        ),
    ]
